package admin

import (
	"html"
	"net/http"
	"strings"
)

// handleDashboard is the private operator page. Its API calls use the same
// authenticated session and CSRF protection as the rest of the admin API.
func (m *Mux) handleDashboard(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		writeError(w, http.StatusMethodNotAllowed, "METHOD_NOT_ALLOWED", "GET only")
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("Content-Security-Policy", "default-src 'none'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'")
	_, _ = w.Write([]byte(strings.ReplaceAll(dashboardHTML, "__CSRF__", html.EscapeString(csrfToken(r)))))
}

const dashboardHTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="__CSRF__"><title>Replx Edge · Control room</title>
<style>
:root{color-scheme:dark;--ink:#e8f0f1;--muted:#9bb2bd;--line:#314b58;--panel:#182d38;--deep:#101f29;--accent:#79d5d0;--warn:#f3bd78;--bad:#f18d86}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#0b1a23;color:var(--ink);font:15px/1.5 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
button,input,select{font:inherit}button,select,input{color:inherit}button{cursor:pointer}a{color:var(--accent)}:focus-visible{outline:3px solid var(--warn);outline-offset:3px}
.shell{display:grid;grid-template-columns:230px minmax(0,1fr);min-height:100vh}.rail{position:sticky;top:0;height:100vh;padding:27px 20px;border-right:1px solid var(--line);background:var(--deep);display:flex;flex-direction:column}.brand{font-size:22px;font-weight:760;letter-spacing:-.055em}.brand small{display:block;color:var(--accent);font-size:11px;letter-spacing:.22em;text-transform:uppercase;font-weight:700;margin-top:1px}.rail nav{display:grid;gap:6px;margin-top:58px}.rail nav a{display:block;padding:10px 12px;border-radius:9px;color:var(--muted);text-decoration:none}.rail nav a:hover,.rail nav a:focus-visible{background:#203b47;color:var(--ink)}.rail-foot{margin-top:auto;font-size:12px;color:var(--muted)}.rail-foot a{display:block;margin-top:8px}.rail-foot form{margin-top:18px}.link-button{background:none;border:0;padding:0;color:var(--muted);text-decoration:underline}
main{min-width:0;padding:34px clamp(20px,4vw,68px) 80px;max-width:1500px;width:100%;margin:auto}.eyebrow{text-transform:uppercase;color:var(--accent);font-size:11px;font-weight:750;letter-spacing:.2em}h1{font-size:clamp(32px,4.5vw,58px);font-weight:690;letter-spacing:-.055em;line-height:1.08;margin:10px 0 16px}.lede{color:var(--muted);max-width:650px;font-size:16px;margin:0}.mast{display:flex;justify-content:space-between;gap:20px;align-items:start;padding-bottom:32px;border-bottom:1px solid var(--line)}.stamp{font-size:12px;color:var(--muted);white-space:nowrap;margin-top:14px}.status{display:inline-flex;gap:8px;align-items:center;color:var(--accent);font-weight:650}.dot{width:8px;height:8px;border-radius:100%;background:currentColor;box-shadow:0 0 0 4px #79d5d01a}.status.warn{color:var(--warn)}.status.bad{color:var(--bad)}
.section{padding:32px 0;border-bottom:1px solid var(--line)}.section-head{display:flex;align-items:end;justify-content:space-between;gap:14px;margin-bottom:18px}.section h2{font-size:22px;letter-spacing:-.035em;margin:0}.section p{color:var(--muted);margin:4px 0 0}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.card{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:19px;min-width:0}.card .label{font-size:12px;text-transform:uppercase;letter-spacing:.12em;color:var(--muted);font-weight:700}.metric{font-size:clamp(26px,3vw,39px);letter-spacing:-.05em;font-weight:700;line-height:1.15;margin:13px 0 5px;font-variant-numeric:tabular-nums}.hint{color:var(--muted);font-size:13px}.bar{height:6px;background:#2a4652;border-radius:4px;margin:17px 0 8px;overflow:hidden}.bar span{display:block;height:100%;width:0;background:var(--accent);border-radius:4px}.storage{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.split{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(270px,.8fr);gap:12px}.feed{display:grid;gap:0}.feed-row{display:flex;justify-content:space-between;gap:16px;padding:12px 0;border-bottom:1px solid var(--line)}.feed-row:last-child{border-bottom:0}.feed-row span:last-child{color:var(--muted);text-align:right}.tag{border:1px solid var(--line);border-radius:99px;padding:4px 9px;font-size:12px;color:var(--muted)}
label{display:grid;gap:6px;color:var(--muted);font-size:13px;font-weight:600}input,select{width:100%;background:#0e202b;border:1px solid #47606c;border-radius:8px;padding:10px 11px;color:var(--ink)}input::placeholder{color:#728b97}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:18px 0}.actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.button{border:1px solid var(--accent);background:var(--accent);color:#09252a;padding:10px 16px;border-radius:8px;font-weight:750}.button:hover{filter:brightness(1.08)}.button.secondary{background:transparent;color:var(--accent)}.message{font-size:13px;color:var(--muted)}.message.error{color:var(--bad)}.message.ok{color:var(--accent)}.wide{grid-column:1/-1}.quiet{font-size:13px;color:var(--muted)}
@media(max-width:900px){.shell{display:block}.rail{position:relative;height:auto;display:block;border-right:0;border-bottom:1px solid var(--line);padding:16px 20px}.rail nav{display:flex;flex-wrap:wrap;margin-top:14px}.rail-foot{display:none}.grid,.storage{grid-template-columns:repeat(2,minmax(0,1fr))}.split{grid-template-columns:1fr}.mast{display:block}}@media(max-width:590px){.grid,.storage,.form-grid{grid-template-columns:1fr}main{padding:24px 18px 60px}.stamp{white-space:normal}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
</style></head><body><div class="shell"><aside class="rail"><div class="brand">replx<span style="color:var(--accent)">.</span><small>Edge control room</small></div><nav aria-label="Admin sections"><a href="#overview">Overview</a><a href="#cache">Cache</a><a href="#storage">Storage</a><a href="#people">People &amp; quality</a><a href="#settings">Settings</a></nav><div class="rail-foot">Private administrator access<a href="/admin/onboarding">Plex connection</a><a href="/admin/spike">Compatibility tests</a><form action="/admin/logout" method="post"><input type="hidden" name="csrf" value="__CSRF__"><button class="link-button" type="submit">Sign out</button></form></div></aside>
<main><header class="mast" id="overview"><div><div class="eyebrow">Your Plex fast path</div><h1>Know what is ready.</h1><p class="lede">See what Replx has warmed, how much space it uses, and the playback limits that apply to each person.</p></div><div class="stamp"><span id="server-status" class="status warn"><span class="dot"></span>Checking</span><div id="updated-at">Loading current state</div></div></header>
<section class="section" aria-labelledby="overview-title"><div class="section-head"><div><h2 id="overview-title">At a glance</h2><p>Live counters from this Replx Edge instance.</p></div><button id="refresh" class="button secondary" type="button">Refresh</button></div><div class="grid"><article class="card"><div class="label">Cache hit rate</div><div class="metric" id="hit-rate">—</div><div class="hint" id="hit-detail">Loading</div></article><article class="card"><div class="label">Warmed pages</div><div class="metric" id="warm-count">—</div><div class="hint" id="warm-detail">Loading</div></article><article class="card"><div class="label">Most recent preload</div><div class="metric" id="last-warm">—</div><div class="hint">Latest completed cache warming activity.</div></article></div></section>
<section class="section" id="cache" aria-labelledby="cache-title"><div class="section-head"><div><h2 id="cache-title">What Replx keeps ready</h2><p>Private pages stay separated by Plex user. Continue Watching updates from playback activity.</p></div><span class="tag">User scoped</span></div><div class="split"><div class="card feed"><div class="feed-row"><span>Collection pages</span><span id="collection-inventory">Full windows for active users · up to 2 hours</span></div><div class="feed-row"><span>Posters</span><span>Local artwork · up to 7 days</span></div><div class="feed-row"><span>Library and metadata</span><span id="library-inventory">Short lived browse copies</span></div><div class="feed-row"><span>Home and library rows</span><span id="home-inventory">Short lived; personalized rows stay private</span></div><div class="feed-row"><span>Continue Watching</span><span id="watch-inventory">Live refresh after playback changes</span></div></div><div class="card"><div class="label">Warm process</div><div class="metric" id="tracked">—</div><div class="hint">Pages tracked for background refresh</div><div class="feed-row"><span>Refresh errors</span><span id="warm-errors">—</span></div><div class="feed-row"><span>Stale pages served</span><span id="stale-count">—</span></div><p class="quiet">A cache copy is used only while the Plex user remains authorized.</p></div></div></section>
<section class="section" id="storage" aria-labelledby="storage-title"><div class="section-head"><div><h2 id="storage-title">Storage</h2><p>Current use and configured limits on this server.</p></div></div><div class="storage"><div class="card"><div class="label">Browse cache</div><div class="metric" id="cache-size">—</div><div class="hint" id="cache-limit">Loading</div><div class="bar"><span id="cache-bar"></span></div><div class="hint" id="cache-entries">—</div></div><div class="card"><div class="label">Poster cache</div><div class="metric" id="art-size">—</div><div class="hint" id="art-limit">Loading</div><div class="bar"><span id="art-bar"></span></div></div><div class="card"><div class="label">Diagnostics</div><div class="metric" id="diag-size">—</div><div class="hint" id="diag-limit">Loading</div><div class="bar"><span id="diag-bar"></span></div></div></div></section>
<section class="section" id="people" aria-labelledby="people-title"><div class="section-head"><div><h2 id="people-title">People &amp; playback quality</h2><p>Limits apply to the selected Plex user. Leave a field blank to inherit the wider policy.</p></div></div><div class="card"><label for="user-select">Plex user<select id="user-select"><option value="">Loading users…</option></select></label><div class="form-grid"><label>Maximum source width<input id="max-width" type="number" min="1" max="16384" placeholder="No user limit"></label><label>Maximum source height<input id="max-height" type="number" min="1" max="16384" placeholder="No user limit"></label><label>Maximum source bitrate (kbps)<input id="max-bitrate" type="number" min="1" placeholder="No user limit"></label><label>Maximum streaming bitrate (kbps)<input id="max-streaming" type="number" min="1" placeholder="No user limit"></label><label>4K sources<select id="allow-4k"><option value="inherit">Inherit</option><option value="allow">Allow</option><option value="deny">Deny</option></select></label><label>HDR<select id="allow-hdr"><option value="inherit">Inherit</option><option value="allow">Allow</option><option value="deny">Deny</option></select></label><label>Transcoding<select id="allow-transcode"><option value="inherit">Inherit</option><option value="allow">Allow</option><option value="deny">Deny</option></select></label></div><div class="actions"><button id="save-policy" class="button" type="button">Save playback limits</button><span id="policy-message" class="message" role="status"></span></div><p class="quiet">These limits choose permitted sources. Plex app settings and direct Plex access may use different paths.</p></div></section>
<section class="section" id="settings" aria-labelledby="settings-title"><div class="section-head"><div><h2 id="settings-title">Settings</h2><p>Safe live settings. Network addresses, secrets and cache budgets are changed in the server deployment.</p></div></div><div class="card"><div class="form-grid"><label>Playback history retention (days)<input id="playback-retention" type="number" min="1" max="3650"></label><label>Audit history retention (days)<input id="audit-retention" type="number" min="1" max="3650"></label></div><div class="actions"><button id="save-settings" class="button" type="button">Save settings</button><span id="settings-message" class="message" role="status"></span></div></div></section>
</main></div><script>
const $=id=>document.getElementById(id),csrf=document.querySelector('meta[name="csrf-token"]').content;
async function api(path,options={}){const res=await fetch(path,{credentials:'same-origin',cache:'no-store',...options,headers:{...(options.body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{}),...options.headers}});let body;try{body=await res.json()}catch{throw new Error('Replx returned an unreadable response')}if(!res.ok)throw new Error(body.error?.message||'Request failed');return body.data??body}
const fmt=n=>n==null?'—':new Intl.NumberFormat().format(n),bytes=n=>n==null?'—':n<1024?'0 KB':(n/(1024**(n>=1073741824?3:n>=1048576?2:1))).toFixed(1)+' '+(n>=1073741824?'GB':n>=1048576?'MB':'KB');
function setText(id,v){$(id).textContent=v}function storage(prefix,used,budget){setText(prefix+'-size',bytes(used));setText(prefix+'-limit',budget!=null?'of '+bytes(budget)+' configured':'Usage unavailable');$(prefix+'-bar').style.width=used!=null&&budget>0?Math.min(100,100*used/budget)+'%':'0%'}
function message(id,text,ok){const el=$(id);el.textContent=text;el.className='message '+(ok?'ok':'error')}
async function refresh(){try{const [status,cache,storageData]=await Promise.all([api('/api/v1/status'),api('/api/v1/cache'),api('/api/v1/storage')]);const total=(cache.hits||0)+(cache.misses||0);setText('hit-rate',total?Math.round(100*(cache.hits||0)/total)+'%':'—');setText('hit-detail',fmt(cache.hits)+' hits · '+fmt(cache.misses)+' misses since start');const w=cache.warmer||{};setText('warm-count',fmt((w.preloadPages||0)+(w.userWindowPages||0)+(w.userHomePages||0)+(w.userSectionPages||0)));setText('warm-detail','Collections '+fmt(w.userWindowPages||0)+' · Home '+fmt(w.userHomePages||0)+' · Library '+fmt(w.userSectionPages||0)+' · '+fmt(w.refreshed)+' refreshes');setText('tracked',fmt(w.tracked));setText('warm-errors',fmt((w.errors||0)+(w.userWindowErrors||0)+(w.userHomeErrors||0)+(w.userSectionErrors||0)));setText('stale-count',fmt(cache.stale));setText('last-warm',Math.max(w.lastPreloadUnix||0,w.lastWindowUnix||0,w.lastRefreshUnix||0,w.lastHomeUnix||0,w.lastSectionUnix||0)?new Date(Math.max(w.lastPreloadUnix||0,w.lastWindowUnix||0,w.lastRefreshUnix||0,w.lastHomeUnix||0,w.lastSectionUnix||0)*1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'Pending');const inv=cache.inventory?.counts;if(inv){setText('collection-inventory',fmt(inv.fullCollectionWindows||0)+' full windows · up to 2 hours');setText('library-inventory',fmt((inv.sections||0)+(inv.metadata||0))+' browse entries');setText('home-inventory',fmt(inv.hubs||0)+' Home entries');setText('watch-inventory',fmt(inv.cw||0)+' Continue Watching entries')}storage('cache',storageData.cacheBytes,storageData.cacheBudgetBytes);storage('art',storageData.artworkBytes,storageData.artworkBudgetBytes);storage('diag',storageData.diagnosticsBytes,storageData.diagnosticsBudgetBytes);setText('cache-entries',storageData.cacheEntries!=null?fmt(storageData.cacheEntries)+' entries':'Entry count unavailable');const s=$('server-status');s.className='status';s.innerHTML='<span class="dot"></span>'+((status.ok)?'Replx is running':'Needs attention');if(!status.ok)s.classList.add('warn');setText('updated-at','Updated '+new Date().toLocaleTimeString())}catch(e){$('server-status').className='status bad';setText('server-status','Unable to load status');setText('updated-at',e.message)}}
let policy={};async function loadUsers(){try{const data=await api('/api/v1/users?limit=200');const users=data.users||[];const sel=$('user-select');sel.replaceChildren();for(const user of users){const o=document.createElement('option');o.value=user.id;o.textContent=user.friendlyName||user.username||user.type||'Plex user';sel.append(o)}if(!users.length){const o=document.createElement('option');o.textContent='No Plex users found';sel.append(o)}await loadPolicy()}catch(e){message('policy-message',e.message,false)}}
const fields=[['max-width','maxSourceWidth'],['max-height','maxSourceHeight'],['max-bitrate','maxSourceBitrateKbps'],['max-streaming','maxStreamingBitrateKbps']];const tri=[['allow-4k','allow4K'],['allow-hdr','allowHDR'],['allow-transcode','allowTranscode']];async function loadPolicy(){const id=$('user-select').value;if(!id)return;try{const d=await api('/api/v1/users/'+encodeURIComponent(id)+'/policy');policy=d.config||{};for(const [el,key] of fields)$(el).value=policy[key]??'';for(const [el,key] of tri)$(el).value=(policy[key]||'inherit').toLowerCase();message('policy-message',d.configured?'Current limits loaded':'This user inherits the default limits',true)}catch(e){message('policy-message',e.message,false)}}
async function savePolicy(){const id=$('user-select').value;if(!id)return message('policy-message','Select a Plex user first',false);const next={...policy};for(const [el,key] of fields){const raw=$(el).value.trim();if(raw==='')delete next[key];else{const n=Number(raw);if(!Number.isInteger(n)||n<1)return message('policy-message','Enter a positive whole number for each limit',false);next[key]=n}}for(const [el,key] of tri)next[key]=$(el).value;try{await api('/api/v1/users/'+encodeURIComponent(id)+'/policy',{method:'PUT',body:JSON.stringify({name:'Dashboard limits',config:next})});policy=next;message('policy-message','Playback limits saved',true)}catch(e){message('policy-message',e.message,false)}}
async function loadSettings(){try{const d=await api('/api/v1/settings');$('playback-retention').value=d.settings?.['replx.playback_retention_days']??30;$('audit-retention').value=d.settings?.['replx.audit_retention_days']??180}catch(e){message('settings-message',e.message,false)}}
async function saveSettings(){const p=Number($('playback-retention').value),a=Number($('audit-retention').value);if(!Number.isInteger(p)||!Number.isInteger(a)||p<1||a<1||p>3650||a>3650)return message('settings-message','Use whole numbers from 1 to 3650 days',false);try{await api('/api/v1/settings',{method:'PATCH',body:JSON.stringify({'replx.playback_retention_days':p,'replx.audit_retention_days':a})});message('settings-message','Settings saved',true)}catch(e){message('settings-message',e.message,false)}}
$('refresh').addEventListener('click',refresh);$('user-select').addEventListener('change',loadPolicy);$('save-policy').addEventListener('click',savePolicy);$('save-settings').addEventListener('click',saveSettings);refresh();loadUsers();loadSettings();
</script></body></html>`
