"""Build or verify the generated Replx Edge complete specification.

Usage:
    python3 scripts/build_complete_spec.py          # regenerate
    python3 scripts/build_complete_spec.py --check  # fail if stale (CI)
"""
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
order = [
    'README.md',
    'docs/product_overview.md',
    'docs/system_architecture.md',
    'docs/adr_001_media_routing_and_origin_exposure.md',
    'docs/plex_owner_auth_and_discovery.md',
    'docs/review_resolution_2026_09_12.md',
    'docs/technical_implementation_specification.md',
    'docs/docker_compose_production.md',
    'docs/cloudflare_tunnel_deployment.md',
    'docs/security_model.md',
    'docs/plex_protocol_route_matrix.md',
    'docs/cache_and_sync_specification.md',
    'docs/playback_policy_media_selection.md',
    'docs/database_schema.md',
    'docs/admin_api_and_ui.md',
    'docs/diagnostics_observability.md',
    'docs/client_compatibility_testing.md',
    'docs/spike_runbook.md',
    'docs/configuration_reference.md',
    'docs/operations_runbook.md',
    'docs/ci_release_backup_upgrade.md',
    'docs/implementation_roadmap.md',
    'docs/acceptance_criteria.md',
    'deploy/media_fallback_design.md',
    'deploy/compose.yml',
    'deploy/.env.example',
]

parts = [
    '# Replx Edge Complete Specification\n',
    '> Generated from canonical source files. Do not edit this file directly.\n'
]
for rel in order:
    p = root / rel
    if not p.exists():
        raise SystemExit(f'Missing canonical document: {rel}')
    parts.append(f'\n\n---\n\n## Source: `{rel}`\n\n')
    text = p.read_text(encoding='utf-8')
    if rel.endswith('.yml') or rel.endswith('.example'):
        lang = 'yaml' if rel.endswith('.yml') else 'dotenv'
        parts.append(f'```{lang}\n{text}\n```\n')
    else:
        parts.append(text)

generated = ''.join(parts)
target = root / 'REPLX_EDGE_COMPLETE_SPEC.md'
if '--check' in sys.argv:
    if not target.exists() or target.read_text(encoding='utf-8') != generated:
        raise SystemExit('REPLX_EDGE_COMPLETE_SPEC.md is stale: run scripts/build_complete_spec.py')
    print('spec in sync')
else:
    target.write_text(generated, encoding='utf-8')
    print(target)
